FROM nagadomi/torch7:cuda10.1-cudnn7-devel-ubuntu18.04


###################################### andy zeng #####################################

RUN git clone https://github.com/andyzeng/arc-robot-vision

##### manual build #####

# sudo apt-get install libhdf5-serial-dev hdf5-tools wget
# git clone https://github.com/anibali/torch-hdf5.git
# cd torch-hdf5
# git checkout hdf5-1.10 
# luarocks make hdf5-0-0.rockspec

# luarocks install inn
